apiVersion: v1
kind: Secret
metadata:
  name: mongodb-auth
  namespace: demo
stringData:
  password: thisIs1StrongPassword
  username: root
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-config
  namespace: demo
stringData:
  mongod.conf: |
    net:
      maxIncomingConnections: 20000
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/instance: mongodb
    app.kubernetes.io/name: mongodbs.kubedb.com
  name: mongodb-init-script
  namespace: demo
stringData:
  mongo-initializer.js: |
    // create user for "testDB"
    db.createUser({
      user: 'root',
      pwd: 'changeit',
      roles: [
          {
              role: 'readWrite',
              db: 'testDB',
          },
      ],
    });
    db = new Mongo().getDB("testDB");

    // create sample collection in the "testDB"
    db.createCollection('users', { capped: false });
    db.createCollection('test', { capped: false });

    // insert some sample data into the "testDB"
    db.test.insert([
      { "item": 1 },
      { "item": 2 },
      { "item": 3 },
      { "item": 4 },
      { "item": 5 }
    ]);
type: Opaque
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  annotations:
    meta.helm.sh/chart-name: mongodb
    meta.helm.sh/chart-url: https://bundles.byte.builders/ui/
    meta.helm.sh/chart-version: v0.1.0
  labels:
    app.kubernetes.io/instance: mongodb
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mongodb-options
  name: mongodb
  namespace: demo
spec:
  assemblyPhase: Ready
  componentKinds:
  - group: app.k8s.io
    kind: Application
  - group: kubedb.com
    kind: MongoDB
  - group: ""
    kind: Secret
  - group: ""
    kind: ServiceAccount
  - group: cert-manager.io
    kind: Issuer
  - group: monitoring.coreos.com
    kind: ServiceMonitor
  - group: stash.appscode.com
    kind: Repository
  - group: stash.appscode.com
    kind: BackupConfiguration
  - group: stash.appscode.com
    kind: RestoreSession
  descriptor:
    description: MongoDB Editor UI Options
    icons:
    - src: https://cdn.appscode.com/images/products/kubedb/kubedb-community-icon.png
      type: image/png
    links:
    - description: website
      url: https://byte.builders
    maintainers:
    - email: support@appscode.com
      name: appscode
    type: mongodbs.kubedb.com
  selector:
    matchLabels:
      app.kubernetes.io/instance: mongodb
      app.kubernetes.io/name: mongodbs.kubedb.com
---
apiVersion: kubedb.com/v1alpha2
kind: MongoDB
metadata:
  annotations:
    stash.appscode.com/backup-blueprint: mongodb-backupconfigblueprint
    stash.appscode.com/schedule: '*/7 * * * *'
  name: mongodb
  namespace: demo
spec:
  authSecret:
    name: mongodb-auth
  configSecret:
    name: mongodb-config
  init:
    script:
      secret:
        secretName: mongodb-init-script
  monitor:
    agent: prometheus.io
    prometheus:
      exporter:
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
  storage:
    resources:
      requests:
        storage: 1Gi
    storageClassName: standard
  storageType: Durable
  terminationPolicy: WipeOut
  version: 4.2.3
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/instance: mongodb
    app.kubernetes.io/name: mongodbs.kubedb.com
    release: prometheus-stack
  name: mongodb
  namespace: demo
spec:
  endpoints:
  - honorLabels: true
    interval: 30s
    path: /metrics
    port: metrics
  namespaceSelector:
    matchNames:
    - demo
  selector:
    matchLabels:
      app.kubernetes.io/instance: mongodb
      app.kubernetes.io/name: mongodbs.kubedb.com
---
apiVersion: stash.appscode.com/v1beta1
kind: BackupBlueprint
metadata:
  name: mongodb-backupconfigblueprint
spec:
  backend:
    gcs:
      bucket: stash-testing
      prefix: stash-backup/${TARGET_NAMESPACE}/${TARGET_APP_RESOURCE}/${TARGET_NAME}
    storageSecretName: gcs-secret
  retentionPolicy:
    keepLast: 5
    name: keep-last-5
    prune: true
  schedule: '*/5 * * * *'
  task:
    name: mongodb-backup-4.2.3-v5
