apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: kubeops
  labels:
    ace.appscode.com/feature: kube-prometheus-stack
spec:
  interval: 5m
  timeout: 30m
  releaseName: kube-prometheus-stack
  targetNamespace: monitoring
  storageNamespace: monitoring
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "45.0.0"
      sourceRef:
        kind: HelmRepository
        name: appscode-charts-oci
        namespace: kubeops
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
