apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: monitoring-config
  namespace: kubeops
spec:
  interval: 5m
  timeout: 30m
  releaseName: monitoring-config
  targetNamespace: monitoring
  storageNamespace: monitoring
  chart:
    spec:
      chart: monitoring-config
      version: "v2023.10.1"
      sourceRef:
        kind: HelmRepository
        name: bytebuilders
        namespace: kubeops
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
