apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  annotations:
    meta.helm.sh/chart-name: mongodb
    meta.helm.sh/chart-url: https://bundles.byte.builders/ui/
    meta.helm.sh/chart-version: v0.1.0
  labels:
    app.kubernetes.io/instance: mongodb
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mongodb-options
  name: mongodb
  namespace: demo
spec:
  assemblyPhase: Ready
  componentKinds:
  - group: app.k8s.io
    kind: Application
  - group: kubedb.com
    kind: MongoDB
  - group: ""
    kind: Secret
  - group: ""
    kind: ServiceAccount
  - group: cert-manager.io
    kind: Issuer
  - group: monitoring.coreos.com
    kind: ServiceMonitor
  - group: stash.appscode.com
    kind: Repository
  - group: stash.appscode.com
    kind: BackupConfiguration
  - group: stash.appscode.com
    kind: RestoreSession
  descriptor:
    description: MongoDB Editor UI Options
    icons:
    - src: https://cdn.appscode.com/images/products/kubedb/kubedb-community-icon.png
      type: image/png
    links:
    - description: website
      url: https://byte.builders
    maintainers:
    - email: support@appscode.com
      name: appscode
    type: mongodbs.kubedb.com
  selector:
    matchLabels:
      app.kubernetes.io/instance: mongodb
      app.kubernetes.io/name: mongodbs.kubedb.com
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: mongodb
  namespace: demo
spec:
  ca:
    secretName: mongodb-ca
---
apiVersion: kubedb.com/v1alpha2
kind: MongoDB
metadata:
  name: mongodb
  namespace: demo
spec:
  init:
    waitForInitialRestore: true
  monitor:
    agent: prometheus.io/builtin
    prometheus:
      exporter:
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
  sslMode: requireSSL
  storage:
    resources:
      requests:
        storage: 1Gi
    storageClassName: standard
  storageType: Durable
  terminationPolicy: WipeOut
  tls:
    issuerRef:
      apiGroup: cert-manager.io
      kind: Issuer
      name: mongo-ca
  version: 4.2.3
---
apiVersion: stash.appscode.com/v1alpha1
kind: Repository
metadata:
  labels:
    app.kubernetes.io/instance: mongodb
    app.kubernetes.io/name: mongodbs.kubedb.com
  name: mongodb-init-repo
  namespace: demo
spec:
  backend:
    gcs:
      bucket: stash-testing
      prefix: /demo/mongodb
    storageSecretName: gcs-secret
---
apiVersion: stash.appscode.com/v1alpha1
kind: Repository
metadata:
  labels:
    app.kubernetes.io/instance: mongodb
    app.kubernetes.io/name: mongodbs.kubedb.com
  name: mongodb-repo
  namespace: demo
spec:
  backend:
    gcs:
      bucket: stash-testing
      prefix: /demo/mongodb
    storageSecretName: gcs-secret
---
apiVersion: stash.appscode.com/v1beta1
kind: BackupConfiguration
metadata:
  labels:
    app.kubernetes.io/instance: mongodb
    app.kubernetes.io/name: mongodbs.kubedb.com
  name: mongodb
  namespace: demo
spec:
  repository:
    name: mongodb-repo
  retentionPolicy:
    keepLast: 5
    name: keep-last-5
    prune: true
  schedule: '*/5 * * * *'
  target:
    ref:
      apiVersion: appcatalog.appscode.com/v1alpha1
      kind: AppBinding
      name: mongodb
  task:
    name: mongodb-backup-4.2.3-v5
---
apiVersion: stash.appscode.com/v1beta1
kind: RestoreSession
metadata:
  labels:
    app.kubernetes.io/instance: mongodb
    app.kubernetes.io/name: mongodbs.kubedb.com
  name: mongodb-init
  namespace: demo
spec:
  repository:
    name: mongodb-init-repo
  rules:
  - snapshots:
    - latest
  target:
    ref:
      apiVersion: appcatalog.appscode.com/v1alpha1
      kind: AppBinding
      name: mongodb
  task:
    name: mongodb-restore-4.2.3-v5
