apiVersion: v1
kind: Secret
metadata:
  name: mongodb-config
  namespace: demo
stringData:
  mongod.conf: |
    net:
      maxIncomingConnections: 20000
type: Opaque
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: mongodb
  namespace: demo
spec:
  ca:
    secretName: mongodb-ca
---
apiVersion: kubedb.com/v1alpha2
kind: MongoDB
metadata:
  annotations:
    stash.appscode.com/backup-blueprint: mongodb-backupblueprint
    stash.appscode.com/schedule: '*/7 * * * *'
  name: mongodb
  namespace: demo
spec:
  configSecret:
    name: mongodb-config
  monitor:
    agent: prometheus.io/operator
    prometheus:
      exporter:
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
      serviceMonitor:
        interval: 30s
        labels:
          release: prometheus-stack
  sslMode: requireSSL
  storage:
    resources:
      requests:
        storage: 1Gi
    storageClassName: standard
  storageType: Durable
  terminationPolicy: WipeOut
  tls:
    issuerRef:
      apiGroup: cert-manager.io
      kind: Issuer
      name: mongo-ca
  version: 4.2.3
---
apiVersion: stash.appscode.com/v1beta1
kind: BackupBlueprint
metadata:
  name: mongodb-backupblueprint
spec:
  backend:
    gcs:
      bucket: stash-testing
      prefix: stash-backup/${TARGET_NAMESPACE}/${TARGET_APP_RESOURCE}/${TARGET_NAME}
    storageSecretName: gcs-secret
  retentionPolicy:
    keepLast: 5
    name: keep-last-5
    prune: true
  schedule: '*/5 * * * *'
  task:
    name: mongodb-backup-4.2.3-v5
