apiVersion: v1
kind: Secret
metadata:
  name: elasticsearch-auth
  namespace: demo
stringData:
  password: thisIs1StrongPassword
  username: elastic
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: elasticsearch-config
  namespace: demo
stringData:
  elasticsearch.yml: 'node.processors: 2'
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: elasticsearch
  namespace: demo
spec:
  selfSigned: {}
---
apiVersion: kubedb.com/v1alpha2
kind: Elasticsearch
metadata:
  name: elasticsearch
  namespace: demo
spec:
  authSecret:
    name: elasticsearch-auth
  configSecret:
    name: elasticsearch-config
  enableSSL: true
  monitor:
    agent: prometheus.io/operator
    prometheus:
      exporter:
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
      serviceMonitor:
        interval: 10s
        labels:
          release: prometheus-stack
  replicas: 3
  storage:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
    storageClassName: linode-block-storage
  storageType: Durable
  tls:
    issuerRef:
      apiGroup: cert-manager.io
      kind: Issuer
      name: elasticsearch
  version: xpack-7.13.2
---
apiVersion: stash.appscode.com/v1alpha1
kind: Repository
metadata:
  name: elasticsearch-repo
  namespace: demo
spec:
  backend:
    gcs:
      bucket: kubedb-testing
      prefix: /elasticsearch
    storageSecretName: gcs-secret
---
apiVersion: stash.appscode.com/v1beta1
kind: BackupConfiguration
metadata:
  name: elasticsearch
  namespace: demo
spec:
  interimVolumeTemplate:
    metadata:
      name: elasticsearch-backup-tmp-storage
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      storageClassName: linode-block-storage
  repository:
    name: elasticsearch-repo
  retentionPolicy:
    keepLast: 5
    name: keep-last-5
    prune: true
  runtimeSettings:
    container:
      securityContext:
        runAsGroup: 0
        runAsUser: 0
  schedule: '*/5 * * * *'
  target:
    ref:
      apiVersion: appcatalog.appscode.com/v1alpha1
      kind: AppBinding
      name: elasticsearch
  task:
    name: elasticsearch-backup-7.3.2
