apiVersion: v1
kind: Secret
metadata:
  name: redis-auth
  namespace: demo
stringData:
  password: thisIs1StrongPassword
  username: root
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-config
  namespace: demo
stringData:
  redis.conf: |
    databases 10
    maxclients 500
type: Opaque
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: redis-ca
  namespace: demo
spec:
  ca:
    secretName: redis-ca
---
apiVersion: kubedb.com/v1alpha2
kind: Redis
metadata:
  name: redis
  namespace: demo
spec:
  authSecret:
    name: redis-auth
  configSecret:
    name: redis-config
  init:
    waitForInitialRestore: true
  mode: Sentinel
  monitor:
    agent: prometheus.io
    prometheus:
      exporter:
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
  replicas: 3
  sentinelRef:
    name: sentinel
    namespace: demo
  storage:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
    storageClassName: standard
  terminationPolicy: WipeOut
  tls:
    issuerRef:
      apiGroup: cert-manager.io
      kind: Issuer
      name: redis-ca
  version: 6.2.5
---
apiVersion: kubedb.com/v1alpha2
kind: RedisSentinel
metadata:
  name: sentinel
  namespace: demo
spec:
  replicas: 3
  storage:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
    storageClassName: standard
  storageType: Durable
  terminationPolicy: WipeOut
  version: 6.2.5
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/instance: redis
    app.kubernetes.io/name: redises.kubedb.com
    release: prometheus-stack
  name: redis
  namespace: demo
spec:
  endpoints:
  - honorLabels: true
    interval: 30s
    path: /metrics
    port: metrics
  namespaceSelector:
    matchNames:
    - demo
  selector:
    matchLabels:
      app.kubernetes.io/instance: redis
      app.kubernetes.io/name: redises.kubedb.com
---
apiVersion: stash.appscode.com/v1alpha1
kind: Repository
metadata:
  labels:
    app.kubernetes.io/instance: redis
    app.kubernetes.io/name: redises.kubedb.com
  name: redis-init-repo
  namespace: demo
spec:
  backend:
    gcs:
      bucket: stash-testing
      prefix: /demo/redis
    storageSecretName: gcs-secret
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-init-repo-cred
  namespace: demo
stringData:
  password: thisIs1StrongPassword
  username: root
type: Opaque
---
apiVersion: stash.appscode.com/v1alpha1
kind: Repository
metadata:
  labels:
    app.kubernetes.io/instance: redis
    app.kubernetes.io/name: redises.kubedb.com
  name: redis-repo
  namespace: demo
spec:
  backend:
    gcs:
      bucket: stash-testing
      prefix: /demo/redis
    storageSecretName: gcs-secret
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-repo-cred
  namespace: demo
stringData:
  password: thisIs1StrongPassword
  username: root
type: Opaque
---
apiVersion: stash.appscode.com/v1beta1
kind: BackupConfiguration
metadata:
  labels:
    app.kubernetes.io/instance: redis
    app.kubernetes.io/name: redises.kubedb.com
  name: redis
  namespace: demo
spec:
  repository:
    name: redis-repo
  retentionPolicy:
    keepLast: 5
    name: keep-last-5
    prune: true
  schedule: '*/2 * * * *'
  target:
    ref:
      apiVersion: appcatalog.appscode.com/v1alpha1
      kind: AppBinding
      name: redis
---
apiVersion: stash.appscode.com/v1beta1
kind: RestoreSession
metadata:
  labels:
    app.kubernetes.io/instance: redis
    app.kubernetes.io/name: redises.kubedb.com
  name: redis-init
  namespace: demo
spec:
  repository:
    name: redis-init-repo
  rules:
  - snapshots:
    - latest
  target:
    ref:
      apiVersion: appcatalog.appscode.com/v1alpha1
      kind: AppBinding
      name: redis
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-encryption-secret
  namespace: demo
stringData:
  RESTIC_PASSWORD: ""
---
apiVersion: core.kubestash.com/v1alpha1
kind: BackupConfiguration
metadata:
  name: redis
  namespace: demo
spec:
  target:
    apiGroup: kubedb.com
    kind: Redis
    name: redis
    namespace: demo
  backends:
    - name: redis-backend
      storageRef:
        name: redis-storage
        namespace: demo
      retentionPolicy:
        name: redis-retention-policy
        namespace: demo
  sessions:
    - name: redis-frequent-backup
      sessionHistoryLimit: 2
      scheduler:
        schedule: "*/5 * * * *"
        jobTemplate:
          backoffLimit: 1
      repositories:
        - name: redis-repo
          backend: redis-backend
          directory: /redis-repo
          encryptionSecret:
            name: redis-encryption-secret
            namespace: demo
      addon:
        name: redis-addon
        tasks:
          - name: logical-backup
        jobTemplate:
          spec:
            securityContext:
              runAsUser: 0
              runAsGroup: 0
---
apiVersion: core.kubestash.com/v1alpha1
kind: RestoreSession
metadata:
  name: redis
  namespace: demo
spec:
  target:
    apiGroup: kubedb.com
    kind: Redis
    name: redis
    namespace: demo
  dataSource:
    snapshot: latest
    repository: redis-repo
    encryptionSecret:
      name: redis-encryption-secret
      namespace: demo
  addon:
    name: redis-addon
    tasks:
      - name: logical-backup-restore
    jobTemplate:
      spec:
        securityContext:
          runAsUser: 0
          runAsGroup: 0
