apiVersion: v1
kind: Secret
metadata:
  name: mongodb-auth
  namespace: demo
stringData:
  password: thisIs1StrongPassword
  username: root
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-config
  namespace: demo
stringData:
  mongod.conf: |
    net:
      maxIncomingConnections: 40000
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-configserver-config
  namespace: demo
stringData:
  mongod.conf: |
    net:
      maxIncomingConnections: 20000
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-mongos-config
  namespace: demo
stringData:
  mongod.conf: |
    net:
      maxIncomingConnections: 30000
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-shard-config
  namespace: demo
stringData:
  mongod.conf: |
    net:
      maxIncomingConnections: 40000
type: Opaque
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: mongodb
  namespace: demo
spec:
  ca:
    secretName: mongodb-ca
---
apiVersion: kubedb.com/v1alpha2
kind: MongoDB
metadata:
  annotations:
    stash.appscode.com/backup-blueprint: mongodb-backupconfigblueprint
    stash.appscode.com/schedule: '*/7 * * * *'
  name: mongodb
  namespace: demo
spec:
  authSecret:
    name: mongodb-auth
  configSecret:
    name: mongodb-config
  monitor:
    agent: prometheus.io/builtin
    prometheus:
      exporter:
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
  shardTopology:
    configServer:
      configSecret:
        name: mongodb-configserver-config
      replicas: 3
      storage:
        resources:
          requests:
            storage: 1Gi
        storageClassName: standard
    mongos:
      configSecret:
        name: mongodb-mongos-config
      replicas: 2
    shard:
      configSecret:
        name: mongodb-shard-config
      replicas: 3
      shards: 2
      storage:
        resources:
          requests:
            storage: 1Gi
        storageClassName: standard
  sslMode: requireSSL
  storageType: Durable
  terminationPolicy: WipeOut
  tls:
    issuerRef:
      apiGroup: cert-manager.io
      kind: Issuer
      name: mongo-ca
  version: 4.2.3
---
apiVersion: stash.appscode.com/v1beta1
kind: BackupBlueprint
metadata:
  name: mongodb-backupconfigblueprint
spec:
  backend:
    gcs:
      bucket: stash-testing
      prefix: stash-backup/${TARGET_NAMESPACE}/${TARGET_APP_RESOURCE}/${TARGET_NAME}
    storageSecretName: gcs-secret
  retentionPolicy:
    keepLast: 5
    name: keep-last-5
    prune: true
  schedule: '*/5 * * * *'
  task:
    name: mongodb-backup-4.2.3-v5
