apiVersion: v1
kind: Secret
metadata:
  name: elasticsearch-admin-cred
  namespace: demo
stringData:
  password: WeakPassword
  username: kibanaserver
type: kubernetes.io/basic-auth
---
apiVersion: v1
kind: Secret
metadata:
  name: elasticsearch-config
  namespace: demo
stringData:
  elasticsearch.yml: 'node.processors: 2'
---
apiVersion: v1
kind: Secret
metadata:
  name: elasticsearch-kibanaro-cred
  namespace: demo
stringData:
  password: WeakPassword
  username: kibanaserver
type: kubernetes.io/basic-auth
---
apiVersion: v1
kind: Secret
metadata:
  name: elasticsearch-kibanaserver-cred
  namespace: demo
stringData:
  password: WeakPassword
  username: kibanaserver
type: kubernetes.io/basic-auth
---
apiVersion: v1
kind: Secret
metadata:
  name: elasticsearch-logstash-cred
  namespace: demo
stringData:
  password: WeakPassword
  username: kibanaserver
type: kubernetes.io/basic-auth
---
apiVersion: v1
kind: Secret
metadata:
  name: elasticsearch-readall-cred
  namespace: demo
stringData:
  password: WeakPassword
  username: kibanaserver
type: kubernetes.io/basic-auth
---
apiVersion: v1
kind: Secret
metadata:
  name: elasticsearch-snapshotrestore-cred
  namespace: demo
stringData:
  password: WeakPassword
  username: kibanaserver
type: kubernetes.io/basic-auth
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: elasticsearch
  namespace: demo
spec:
  selfSigned: {}
---
apiVersion: kubedb.com/v1alpha2
kind: Elasticsearch
metadata:
  name: elasticsearch
  namespace: demo
spec:
  configSecret:
    name: elasticsearch-config
  disableSecurity: true
  enableSSL: true
  internalUsers:
    admin:
      backendRoles:
      - admin
      reserved: true
      secretName: elasticsearch-admin-cred
    kibanaro:
      secretName: elasticsearch-kibanaro-cred
    kibanaserver:
      reserved: true
      secretName: elasticsearch-kibanaserver-cred
    logstash:
      secretName: elasticsearch-logstash-cred
    readall:
      secretName: elasticsearch-readall-cred
    snapshotrestore:
      secretName: elasticsearch-snapshotrestore-cred
  monitor:
    agent: prometheus.io
    prometheus:
      exporter:
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
  replicas: 3
  storage:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
    storageClassName: linode-block-storage
  storageType: Durable
  tls:
    issuerRef:
      apiGroup: cert-manager.io
      kind: Issuer
      name: elasticsearch
  version: searchguard-7.10.2
---
apiVersion: stash.appscode.com/v1alpha1
kind: Repository
metadata:
  name: elasticsearch-repo
  namespace: demo
spec:
  backend:
    gcs:
      bucket: kubedb-testing
      prefix: /elasticsearch
    storageSecretName: gcs-secret
---
apiVersion: stash.appscode.com/v1beta1
kind: BackupConfiguration
metadata:
  name: elasticsearch
  namespace: demo
spec:
  interimVolumeTemplate:
    metadata:
      name: elasticsearch-backup-tmp-storage
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      storageClassName: linode-block-storage
  repository:
    name: elasticsearch-repo
  retentionPolicy:
    keepLast: 5
    name: keep-last-5
    prune: true
  runtimeSettings:
    container:
      securityContext:
        runAsGroup: 0
        runAsUser: 0
  schedule: '*/5 * * * *'
  target:
    ref:
      apiVersion: appcatalog.appscode.com/v1alpha1
      kind: AppBinding
      name: elasticsearch
  task:
    name: elasticsearch-backup-7.3.2
