apiVersion: v1
kind: Secret
metadata:
  name: postgres-auth
  namespace: demo
stringData:
  password: thisIs1StrongPassword
  username: postgres
type: Opaque
---
apiVersion: kubedb.com/v1alpha2
kind: Postgres
metadata:
  annotations:
    stash.appscode.com/backup-blueprint: postgres-backupblueprint
    stash.appscode.com/schedule: '*/7 * * * *'
  name: postgres
  namespace: demo
spec:
  authSecret:
    name: postgres-auth
  clientAuthMode: scram
  init:
    waitForInitialRestore: true
  monitor:
    agent: prometheus.io/operator
    prometheus:
      exporter:
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
      serviceMonitor:
        interval: 30s
        labels:
          release: prometheus-stack
  replicas: 3
  standbyMode: Hot
  storage:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
    storageClassName: standard
  storageType: Durable
  terminationPolicy: WipeOut
  version: "13.2"
---
apiVersion: stash.appscode.com/v1alpha1
kind: Repository
metadata:
  labels:
    app.kubernetes.io/instance: postgres
    app.kubernetes.io/name: postgreses.kubedb.com
  name: postgres-init-repo
  namespace: demo
spec:
  backend:
    gcs:
      bucket: stash-testing
      prefix: /demo/postgres
    storageSecretName: gcs-secret
---
apiVersion: stash.appscode.com/v1beta1
kind: BackupBlueprint
metadata:
  name: postgres-backupblueprint
spec:
  backend:
    gcs:
      bucket: stash-testing
      prefix: stash-backup/${TARGET_NAMESPACE}/${TARGET_APP_RESOURCE}/${TARGET_NAME}
    storageSecretName: gcs-secret
  retentionPolicy:
    keepLast: 5
    name: keep-last-5
    prune: true
  schedule: '*/5 * * * *'
---
apiVersion: stash.appscode.com/v1beta1
kind: RestoreSession
metadata:
  labels:
    app.kubernetes.io/instance: postgres
    app.kubernetes.io/name: postgreses.kubedb.com
  name: postgres-init
  namespace: demo
spec:
  repository:
    name: postgres-init-repo
  rules:
  - snapshots:
    - latest
  target:
    ref:
      apiVersion: appcatalog.appscode.com/v1alpha1
      kind: AppBinding
      name: postgres
