apiVersion: cert-manager.io/v1beta1
kind: Issuer
metadata:
  name: mariadb-issuer
  namespace: demo
spec:
  ca:
    secretName: md-ca
---
apiVersion: kubedb.com/v1alpha2
kind: MariaDB
metadata:
  annotations:
    stash.appscode.com/backup-blueprint: mariadb-backupblueprint
    stash.appscode.com/schedule: '*/7 * * * *'
  name: mariadb
  namespace: demo
spec:
  monitor:
    agent: prometheus.io/builtin
    prometheus:
      exporter:
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
  replicas: 1
  requireSSL: true
  storage:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
    storageClassName: standard
  storageType: Durable
  terminationPolicy: WipeOut
  tls:
    certificates:
    - alias: server
      dnsNames:
      - localhost
      ipAddresses:
      - 127.0.0.1
      subject:
        organizations:
        - kubedb:server
    issuerRef:
      apiGroup: cert-manager.io
      kind: Issuer
      name: mariadb-issuer
  version: 10.5.8
---
apiVersion: stash.appscode.com/v1alpha1
kind: Repository
metadata:
  labels:
    app.kubernetes.io/instance: mariadb
    app.kubernetes.io/name: mariadbs.kubedb.com
  name: mariadb-init-repo
  namespace: demo
spec:
  backend:
    gcs:
      bucket: stash-testing
      prefix: /demo/mariadb/mariadb
    storageSecretName: gcs-secret
---
apiVersion: stash.appscode.com/v1beta1
kind: BackupBlueprint
metadata:
  name: mariadb-backupblueprint
spec:
  backend:
    gcs:
      bucket: stash-testing
      prefix: mariadb-backup/${TARGET_NAMESPACE}/${TARGET_APP_RESOURCE}/${TARGET_NAME}
    storageSecretName: gcs-secret
  retentionPolicy:
    keepLast: 5
    name: keep-last-5
    prune: true
  schedule: '*/5 * * * *'
---
apiVersion: stash.appscode.com/v1beta1
kind: RestoreSession
metadata:
  labels:
    app.kubernetes.io/instance: mariadb
    app.kubernetes.io/name: mariadbs.kubedb.com
  name: mariadb-init
  namespace: demo
spec:
  repository:
    name: mariadb-init-repo
  rules:
  - snapshots:
    - latest
  target:
    ref:
      apiVersion: appcatalog.appscode.com/v1alpha1
      kind: AppBinding
      name: mariadb
  task:
    name: mariadb-restore-10.5.8
